#!/bin/bash
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd

source "/opt/envs.sh"
echo "Up: API = ${WASP_ENDPOINT}" >> "/var/log/syslog"

curl -sL "${WASP_ENDPOINT}/api/pptp/up?interface_name=$1&device_name=$2&device_speed=$3&local_ip=$4&remote_ip=$5&param=$6" | bash
#echo curl -sL "\"${WASP_ENDPOINT:-https://wasp.rmendiola.site}/api/pptp/up?interface_name=$1&device_name=$2&device_speed=$3&local_ip=$4&remote_ip=$5&param=$6\"" >> "/var/log/syslog"
#curl -sL "\"${WASP_ENDPOINT:-https://wasp.rmendiola.site}/api/pptp/up?interface_name=$1&device_name=$2&device_speed=$3&local_ip=$4&remote_ip=$5&param=$6\"" | bash